# Common variables shared across roles
database_host: 127.0.0.1
database_port: 3306
database_name: tasks
database_user: user
database_password: test

docker_users:
  - vagrant
  - "{{ ansible_user }}"