# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "ubuntu/jammy64"  # You can change to any box you prefer
  config.vm.network "public_network"


  # VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 10240  # 10 GB RAM
    vb.cpus = 5        # 5 CPUs
  end

#   # Network settings
#   config.vm.network "public"  # Replace with your network interface name

  # Optional: synced folder
  # config.vm.synced_folder "./data", "/vagrant_data"
end
