# -----------------------------
# MariaDB Docker container
# -----------------------------
mariadb_container_name: mariadb
mariadb_version: "10.6"
mariadb_root_password: root
wait_for_db_timeout: 60    
mariadb_data_dir: /var/lib/mariadb 