---

- name: Get latest kubectl version string
  uri:
    url: "{{ kubectl_version_url }}"
    return_content: yes
  register: kubectl_version

- name: Download kubectl
  get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
    dest: /tmp/kubectl
    mode: "0755"

- name: Install kubectl
  copy:
    src: /tmp/kubectl
    dest: "{{ kubectl_bin_path }}"
    mode: "0755"

- name: Remove temp kubectl
  file:
    path: /tmp/kubectl
    state: absent