docker_repo_url: "https://download.docker.com/linux/ubuntu"
docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_apt_repo: "deb [arch=amd64] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"