apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-v2
  namespace: default
  labels:
    app: manager
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
      version: v2
  template:
    metadata:
      labels:
        app: manager
        version: v2
    spec:
      serviceAccountName: manager-sa
      containers:
      - name: manager
        image: sacumesh/devops-task-manager:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-name
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: db-password