apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-v1
  namespace: default
  labels:
    app: mariadb
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      version: v1
  template:
    metadata:
      labels:
        app: mariadb
        version: v1
    spec:
      serviceAccountName: mariadb-sa
      containers:
      - name: mariadb
        image: mariadb:12.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: db-root-password
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: db-password
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-name
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
