# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "ubuntu/jammy64"  # You can change to any box you prefer
  config.vm.network "public_network"


  # VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 10240  # 10 GB RAM
    vb.cpus = 5        # 5 CPUs
  end

    config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/site.yaml"
    end
end
