---
- name: Download cri-dockerd deb package
  get_url:
    url: "{{ cri_dockerd_deb_url }}"
    dest: "{{ cri_dockerd_deb_path }}"
    mode: '0644'
  become: true

- name: Install cri-dockerd
  apt:
    deb: "{{ cri_dockerd_deb_path }}"
  become: true
  register: cri_dockerd_install

- name: Remove temporary cri-dockerd package
  file:
    path: "{{ cri_dockerd_deb_path }}"
    state: absent
  become: true
  when: cri_dockerd_install is succeeded

- name: Enable and start cri-dockerd service
  systemd:
    name: cri-docker.service
    enabled: yes
    state: started
  become: true