---
- name: Download CNI plugins tarball
  get_url:
    url: "{{ cni_plugin_url }}"
    dest: "{{ cni_plugin_tmp }}"
    mode: '0644'
  become: true
  register: download_result

- name: Check if the download was successful
  fail:
    msg: "Failed to download CNI plugins from {{ cni_plugin_url }}"
  when: download_result is failed

- name: Create CNI plugin install directory
  file:
    path: "{{ cni_install_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Extract CNI plugins to install directory
  unarchive:
    src: "{{ cni_plugin_tmp }}"
    dest: "{{ cni_install_dir }}"
    remote_src: yes
    mode: '0755'
  become: true
  notify: Restart kubelet

- name: Remove temporary CNI tarball
  file:
    path: "{{ cni_plugin_tmp }}"
    state: absent
  become: true