---

kubectl_bin_path: "/usr/local/bin/kubectl"
minikube_download_url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
minikube_bin_path: "/usr/local/bin/minikube"

minikube_memory: "2048"
minikube_cpus: "2"
minikube_driver: "docker"

k8s_user: "vagrant"
