apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80         # Port exposed externally
      targetPort: 80   # Port on the pod
      nodePort: 30080   # Node port (can be in range 30000-32767)
  selector:
    app: nginx