Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "ubuntu/jammy64"

  # Private network (DHCP)
  config.vm.network "private_network", type: "dhcp"

  # Port forwarding
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  # VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2408  # 10 GB RAM
    vb.cpus = 2        # 5 CPUs
  end

  # Ansible provisioner
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/site.yaml"
  end
end
